### ISSUE TITLE
[HLA_Imputation_BEAGLE5.py::ERROR]: Imputation(exon2 / overlap:0.5) failed.

### ISSUE THREAD

**Issue by Aamiralizai** [WansonChoi/CookHLA#13]
Hello @WansonChoi 
I am facing error in the last step of CookHLA pipeline, I used my data (chr6 29mb-34mb) data with the reference data from 1000 genome reference panel however it failed due to the following error
[4] Performing HLA imputation(exon2 / overlap:0.5).

[HLA_Imputation_BEAGLE5.py::ERROR]: Imputation(exon2 / overlap:0.5) failed.

Traceback (most recent call last):
  File "/share/home/aamir/CookHLA-master/src/HLA_Imputation_BEAGLE5.py", line 555, in IMPUTE
    subprocess.run(re.split('\s+', command), check=True, stdout=f_log, stderr=f_log)
  File "/share/home/aamir/anaconda3/envs/CookHLA/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-Djava.io.tmpdir=MyHLAImputation/data+1000G_REF.EAS.javatmpdir', '-Xmx2000m', '-jar', './dependency/beagle5.jar', 'gt=MyHLAImputation/data1+1000G_REF.EAS.MHC.QC.vcf', 'ref=MyHLAImputation/1000G_REF.EAS.chr6.hg18.29mb-34mb.inT1DGC.exon2.phased.vcf', 'out=MyHLAImputation/data1+1000G_REF.EAS.MHC.QC.exon2.0.5.raw_imputation_out', 'impute=true', 'gp=true', 'overlap=0.5', 'err=0.00350207085828343', 'map=MyHLAImputation/data1+1000G_REF.EAS.mach_step.avg.clpsB.exon2.txt', 'window=5', 'ne=10000', 'nthreads=1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CookHLA.py", line 1035, in <module>
    f_save_IMPUTATION_INPUT=args.save_IMPUTATION_INPUT)
  File "CookHLA.py", line 862, in CookHLA
    f_measureAcc_v2=f_measureAcc_v2)
  File "/share/home/aamir/CookHLA-master/src/HLA_Imputation_BEAGLE5.py", line 154, in __init__
    self.__AVER__, self.dict_ExonN_AGM[_exonN], f_prephasing=f_prephasing)
  File "/share/home/aamir/CookHLA-master/src/HLA_Imputation_BEAGLE5.py", line 559, in IMPUTE
    raise CookHLAImputationError(std_ERROR_MAIN_PROCESS_NAME + "Imputation({} / overlap:{}) failed.\n".format(_exonN, _overlap))
src.CookHLAError.CookHLAImputationError:
[HLA_Imputation_BEAGLE5.py::ERROR]: Imputation(exon2 / overlap:0.5) failed.
Can you please guide me to solve this issue

**Comment by WansonChoi** [comment]
@Aamiralizai 

Hi, Aamiralizai,

Thank you for your interest in CookHLA.

Could try the imputation with Beagle 4 instead of 5? (with the '-bgl4' argument.)

If it fails again, then please attach the log files of the failed imputations. (ex. "MyHLAImputation/data1+1000G_REF.EAS.MHC.QC.exon2.0.5.raw_imputation_out.log")

**Comment by Aamiralizai** [comment]
@WansonChoi 
Thank you for your response, the problem was in my .fam file.

**Comment by xingejun** [comment]
Hi @Aamiralizai ,

The same error came up in my running. Could you please tell me what had happened in your .fam file?

I will be very grateful if you can reply.

Thank you very much!
Guo

**Comment by Aamiralizai** [comment]
Hi @Xingejun,
You can have a look to at any reference .fam file and compared with you .fam file if there is any difference in the FID and IID, In my case the the error was due to FID and IID in my .fam file.

**Comment by xingejun** [comment]
Hi @Aamiralizai ,

Thanks. My issue had been solved and it is not in the .fam. Actually I didn't figure out what happened.

**Comment by PoojaMiddha** [comment]
Hi @xingejun, 
I am encountering a similar problem. Can you share how you solved the problem?

**Comment by Aamiralizai** [comment]
@PoojaMiddha 
try --beagle4   instead of beagle5

**Comment by xingejun** [comment]
Hi @PoojaMiddha ,

I have met a lot of problems at that time when I was trying running it. And a lot of solutions I have tried so I can't sure which one works. I thought it mostly likely  because I changed my running environment suitbale for java or memory set.
