### ISSUE TITLE
Fail to reproduce the toy example

### ISSUE THREAD

**Issue by wgmao** [WansonChoi/CookHLA#5]
Thank you for developing this wonderful tools. I have two questions for you as I failed to reproduce the toy example.

1. When I tried to generate the adaptive genetic map using the toy dataset available in the folder, I got the following errors. I have created `MyAGM` folder in the working directory, so I don't know if I missed anything.
```
python -m MakeGeneticMap -i example/1958BC.hg19 -hg 19 -ref 1000G_REF/1000G_REF.EUR.chr6.hg18.29mb-34mb.inT1DGC -o MyAGM/1958BC+1000G_REF.EUR
Namespace(human_genome='19', input='example/1958BC.hg19', out='MyAGM/1958BC+1000G_REF.EUR', reference='1000G_REF/1000G_REF.EUR.chr6.hg18.29mb-34mb.inT1DGC')
sh: 1: None: not found
Traceback (most recent call last):
  File "/home/wem26/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wem26/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wem26/CookHLA/MakeGeneticMap/__main__.py", line 102, in <module>
    CookHLA_MakeGeneticMap(args.input, args.human_genome, args.reference, args.out)
  File "/home/wem26/CookHLA/MakeGeneticMap/__main__.py", line 39, in __init__
    self.GeneticMap = MakeGeneticMap(_input, _reference, _out)
  File "/home/wem26/CookHLA/MakeGeneticMap/MakeGeneticMap.py", line 26, in MakeGeneticMap
    N_sample_target = getSampleNumbers(_input+'.fam')
  File "/home/wem26/CookHLA/src/checkInput.py", line 26, in getSampleNumbers
    with open(_fam, 'r') as f_fam:
FileNotFoundError: [Errno 2] No such file or directory: 'MyAGM/1958BC.hg19.COPY.LiftDown_hg18.fam'
```

2. Is there a way to merge reference panels, e.g., all 1000Genome panels?

**Comment by WansonChoi** [comment]
@wgmao 

Hi. Thank you for your interest in CookHLA.


(1)

Before investigating, did you create and apply a new virtual conda environment for CookHLA with the given YML file? ('CookHLA_[YOUR_OS].yml')

If you did the above, then there would be an PLINK error log file('MyAGM/1958BC.hg19.COPY.LiftDown_hg18.log', supposedly.) Can you share it? 
It seems PLINK failed to generate 'MyAGM/1958BC.hg19.COPY.LiftDown_hg18.{bed,bim,fam}' files in this code block(https://github.com/WansonChoi/CookHLA/blob/56df6e2d5f656179f4be5fb73e443b7e2804bfc3/src/checkInput.py#L210)



(2)
The reference panels for each population were divided from one panel with all samples(n=2504). I pushed them in the '1000G_REF/' directory. (1000G_REF.ALL.chr6.hg18.29mb-34mb.inT1DGC.{bed,bim,fam, ...}).

**Comment by wgmao** [comment]
Thank you for your suggestions.

1) I didn't create a new virtual environment, but I put all external software in the `dependency` folder and installed the requirements. Is it required to create the environment with the given YML file? I just found that the list of dependency software is much longer than that listed in the `README.md`. Maybe I miss a lot of the dependency package for R and python.

**Comment by WansonChoi** [comment]
@wgmao 

To control other unexpected variables, It is recommended to create and use a new conda environment, but I think this error is not highly related to the error. So, let's suspect other things first.

I guess the error is more related to the preprocesses that the 'src/checkInput.py' performs. I recently modified it, so apply this update(the commit 'c873550') and try the 'MakeGeneticMap' module again, please. If it fails with a similar error, then please share the log file(maybe '*.COPY.LiftDown_hg18.log').
