### ISSUE TITLE
Reference 1000G ALL not working?

### ISSUE THREAD

**Issue by afaulconbridge** [WansonChoi/CookHLA#9]
Thanks for making this software available. I can successfully impute from the 1000G individual superpopulation files, but I'm seeing an error when I try to use the combined overall 1000G reference panel. Specifically Beagle says:

```ERROR: java.lang.IllegalArgumentException: 3
java.lang.IllegalArgumentException: 3
	at vcf.BitSetGTRec.get(BitSetGTRec.java:171)
	at vcf.BasicGT.allele(BasicGT.java:136)
	at vcf.SplicedGT.allele(SplicedGT.java:104)
	at phase.ImputeBaum.unscaledAlProbs(ImputeBaum.java:151)
	at phase.ImputeBaum.imputeInterval(ImputeBaum.java:124)
	at phase.ImputeBaum.phase(ImputeBaum.java:107)
	at phase.PhaseLS.lambda$runStage2$2(PhaseLS.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

though exactly which exon raises the error doesn't seem to be consistent. Sometimes its 2.1 but also 2.1.5 too.

Have you been able to use the 100G_ALL reference successfully? Is there anything that needs to be changed or checked to work with the larger reference panel?

**Comment by WansonChoi** [comment]
@afaulconbridge 

Hi, Thank you for your interest in CookHLA.

As far as I checked, the 1000G_ALL reference panel worked well with the toy example.

Could you try the imputation again with Bealge4 instead of Beagle5? (Add '-bgl4' argument.) I've seen a similar error(java.lang.IllegalArgumentException) before, but I couldn't figure out the exact cause. At least I know this error sometimes occurs in only Beagle5 and barely occurs with Beagle4.
